use Mix.Config

# For production, we configure the host to read the PORT
# from the system environment. Therefore, you will need
# to set PORT=80 before running your server.
#
# You should also configure the url host to something
# meaningful, we use this information when generating URLs.
#
# Finally, we also include the path to a manifest
# containing the digested version of static files. This
# manifest is generated by the mix phoenix.digest task
# which you typically run after static files are built.
config :crossroads_interface, CrossroadsInterface.Endpoint,
  url: [host: "int.crossroads.net", port: System.get_env("COWBOY_PORT")],
  https: [port: System.get_env("COWBOY_PORT"),
    otp_app: :crossroads_interface,
    keyfile: System.get_env("SSL_KEY_PATH"),
    certfile: System.get_env("SSL_CERT_PATH"),
    cacertfile: System.get_env("SSL_INTERMEDIATE_PATH")],
  cache_static_manifest: "priv/static/manifest.json",
  server: true

# Do not print debug messages in production
config :logger, level: :info

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#config :crossroads_interface, CrossroadsInterface.Endpoint,
  #url: [host: "int.crossroads.net", port: 44300],
  #https: [port: 4430,
    #keyfile: System.get_env("SSL_KEY_PATH"),
    #certfile: System.get_env("SSL_CERT_PATH"),
    #cacertfile: System.get_env("SSL_INTERMEDIATE_PATH")]

  #config :crossroads_interface, CrossroadsInterface.Endpoint,
  #force_ssl: [hsts: true]

# Check `Plug.SSL` for all available options in `force_ssl`.

# If you are doing OTP releases, you need to instruct Phoenix
# to start the server for all endpoints:
#
config :phoenix, :serve_endpoints, true

# You will also need to set the application root to `.` in order
# for the new static assets to be served after a hot upgrade:
#
config :crossroads_interface, CrossroadsInterface.Endpoint, root: "."

# import_config "prod.secret.exs"
